base_dir: data/model
data:
  batch_size: 64
  dataset_dir: data/METR-LA
  graph_pkl_filename: data/sensor_graph/adj_mx.pkl
  test_batch_size: 64
  val_batch_size: 64
log_level: INFO
model:
  cl_decay_steps: 2000
  filter_type: dual_random_walk
  horizon: 12
  input_dim: 2
  l1_decay: 0
  max_diffusion_step: 2
  num_nodes: 207
  num_rnn_layers: 2
  output_dim: 1
  rnn_units: 64
  seq_len: 12
  use_curriculum_learning: true
train:
  base_lr: 0.01
  dropout: 0
  epoch: 1
  epochs: 100
  epsilon: 0.001
  global_step: 20
  log_dir: data/model/dcrnn_DR_2_h_12_64-64_lr_0.01_bs_64_1205102308/
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06
  model_filename: data/model/dcrnn_DR_2_h_12_64-64_lr_0.01_bs_64_1205102308/models-1.6309-20
  optimizer: adam
  patience: 50
  steps:
  - 20
  - 30
  - 40
  - 50
  test_every_n_epochs: 10
